name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 00 * * *' # Runs every day, at midnight
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in pixelrobots posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://pixelrobots.co.uk/feed/"
          #template: '<a href="$url"><img width="140px" src="https://github.com/PixelRobots/PixelRobots/blob/master/images/PixelRobots_Desktop_Wallpaper.png?raw=true"></a>$newline<td><a href="$url">$title</a><br/>$date$newline</br>'
