name: Latest YouTube Videos
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCs6gF5L-7iaoHlTDYpAlgsQ"
          #custom_tags: "videoId/yt:videoId/"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          max_post_count: 6
          #template: "$newline[![$title](https://freshidea.com/jonah/app/youtube-card/?id=$videoId)]($url \"$title\")"
          #template: '<table><tr><td><a href="$url"><img width="140px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg"></a></td>$newline<td><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
          template: '<div class="card" style="box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2); transition: 0.3s; width: 40%"><a href="$url"><img width="100%" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg" alt="YouTube Thumbnail"></a>$newline<div class="container" style="padding: 2px 16px"><a href="$url">$title</a><br/>$date$newline</div></div>$newline'
          committer_email: "richard.hooper@pixelrobots.co.uk"
